### ISSUE TITLE
CMS: Medicaid - LT visits needs to merge visit dates with 1 day differences as one

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization#111] opened 2023-07-25 14:36 UTC
LT - long term care claims are submitted in monthly, if the claim contains only one day difference in claim dates merge the visit dates into one such that we do not have multiple visit dates for one stay in a long term care for a patient that last more than a month.

**Comment by stephanieshong** [comment] 2023-07-25 19:55
lt_visit_detail rollup to lt_visit_occurrence - Long term care claims come in monthly chunks even though the visit is continuous with one day difference. For example,  as the calendar date moves from Feb 28 to March 1 we have two claims instead of one. Therefore, these monthly claims should be merged to into one visit instead of having multiple visits from the claim dates found in the record for the same patient.  They are continuous visit with one day difference for the same patient.

**Comment by chrisroederucdenver** [comment] 2023-09-20 14:27
FYI, starting as my primary effort today.

**Comment by chrisroederucdenver** [comment] 2023-10-11 15:29
re-started this week after some leave. [Analysis workbook here](https://unite.nih.gov/workspace/vector/view/ri.vector.main.workbook.47e25b53-b1d9-4e9b-85d6-53119852cb78?branch=master).

**Comment by chrisroederucdenver** [comment] 2023-10-16 19:20
Looks like the ancestor/descendant relationships in OMOP for in-patient and out-patient concepts (9201, 9202) to the medicare concept for hospital code A0 (38004515) are upside down. This makes code in cross-walk creation create a 1-to-many mapping that results in multiple rows.  [Ticket 120 here.](https://github.com/National-COVID-Cohort-Collaborative/Data-Ingestion-and-Harmonization/issues/120)

**Comment by chrisroederucdenver** [comment] 2023-11-07 18:16
PR ready with a first() to pick one of the two alues.[PR]( https://unite.nih.gov/workspace/data-integration/code/repos/ri.stemma.main.repository.2fb345e3-d595-480a-a26e-26fe6846760e/pulls/ri.pull-request.main.pull-request.288a009d-41a2-47c9-ae5f-21442d2065fc/overview)

Within just LT data, without a fix, you get 214k rows in visit_occurrence. With a fix you get 118k. This is confirmed when you see that there are either 95k or 2x 95k rows from A0.
To set the context, within all of medicaid (no filter) the visit_occurrence table has 35m rows.

**Comment by chrisroederucdenver** [comment] 2023-11-14 22:09
merged Nov. 10 
@stephanieshong I don't have permission to close.

**Comment by stephanieshong** [comment] 2023-11-14 22:36
@chrisroederucdenver -Thank you. Completed the merge and build over the weekend, 11/11/23! Closing.

**Closed** 2023-11-14 22:36 UTC
